---
output:
  html_document: 
    toc: true
    toc_float: true
---

<link rel="stylesheet" href="styles.css" type="text/css">

<span style="color:cornflowerblue">**If you have no access to any of my publications, feel free to request a pdf copy.**</span>

------------------

### Research interests

My research interests lie broadly in community ecology and macroecology, in particular in what determines the dynamics and stability of ecological networks, and how these properties in turn affect the local and regional pattern of biodiversity and ecosystem functioning. I am fascinated by the nature of the relationships among these properties, how they scale trophically and spatially, and how they are regulated by environmental change and stochasticity. I am a theoretical ecologist and data scientist, and mainly use computer simulations and database analysis to answer these interesting questions.



------------------

### Projects

**Aquatic ecology and environment**

During my Master's study, my research is mainly in the area of aquatic ecology and environment. My Master thesis studied the mechanism underlying algal blooms in the river^8^. In field, I investigated the effect of climatic and hydrological conditions on the formation of diatom blooms in the Hanjiang River. With the effects being clear, I further put forward a feasible flushing strategy for algal bloom control^5^. During this stage, I also actively participated in other projects related to stable isotope ecology^7^ and aquatic toxicology^6^.

**The multidimensionality of ecological stability**

Ecological stability is a multifaceted concept, incorporating components such as variability, resistance, resilience, persistence, and robustness. Understanding and predicting the relationships among these many components of stability is fundamental to the optimal management of both biodiversity and ecosystem functioning. In spite of this, the multidimensionality of ecological stability remains remarkably understudied, with most research focussing on one or two components in isolation. We know worryingly little about the mechanisms underpinning relationships among components of stability and whether there are any general features of these that are common across different types of ecosystem or disturbance. In my PhD project, I explored the effect of perturbations on both the relationships between stability components and the predictability of these components.

i) I examined the effects of perturbation intensity using theoretical simulations. By analysing the dynamics of food-webs following perturbations of different strengths, I discover that the predictability of stability components and the strength of relationships between them decrease with increasing perturbation strength. Importantly, this decoupling effect of strong perturbations was consistent across a variety of food-web structures. 

ii) I tested these predictions in natural communities using data from the Nutrient Network - a globally distributed grassland experimental system - to examine whether perturbations decouple relationships between components of stability at the global scale.

iii) Natural systems encounter a large variety of perturbations that vary in their spatial extents, durations, frequencies, and intensities. While most models and experiments predicting ecological responses have typically applied static steady-state approaches that focus on a single perturbation event or the mean level of environmental change, few have incorporated environmental stochasticity. Moreover, those that do tend to incorporate it as white noise. In \Chapref{Stochasticity}, using food-web modeling I explored how the response and predictability of different stability components are regulated by key characteristics of environmental stochasticity, including its temporal autocorrelation (colour), and the strength of correlations in the responses of species to it. I found that different stability components showed distinct responding patterns to changing temporal autocorrelation of environmental noise. Increasing environmental autocorrelation stabilize communities in some dimensions yet simultaneously destabilize them in others. In contrast, the predictability of stability decreases consistently as the temporal autocorrelation of environmental noise becomes increasingly positive. This finding demonstrates the fundamental role played by environmental stochasticity in determining the dynamics and stability of ecosystems and challenges the credibility of models that overlook it or simply incorporate it as white noise. 

Taken together, results of the research described in this thesis highlight important difference between different components of ecological stability in their response to external perturbations and environmental stochasticity, and emphasize the necessity of exploring further the multifaceted nature of ecological stability.

------------------

### Publications


1. <span style="color:cornflowerblue">**Q. Yang**</span>, F. Mike, A.L. Jackson, I. Donohue. The predictability of ecological stability in a noisy world. **Nature Ecology & Evolution**. accepted.
2. I. Donohue, O.L. Petchey, S. Kefi, A. Genin, A.L. Jackson, <span style="color:cornflowerblue">**Q. Yang**</span>, N.E. O’Connor. (2017) Loss of predator species, not intermediate consumers, triggers rapid and dramatic extinction cascades. [**Global Change Biology**. 23: 2962-2972.](https://onlinelibrary.wiley.com/doi/full/10.1111/gcb.13703)
3. I. Donohue, H. Hillebrand, J.M. Montoya, O.L. Petchey, S.L. Pimm, M.S. Fowler, K. Healy, A.L. Jackson, M. Lurgi, D. McClean, N.E. O’Connor, E.J. O’Gorman, <span style="color:cornflowerblue">**Q. Yang**</span>. (2016) Navigating the complexity of ecological stability. [**Ecology Letters**, 19(9): 1172-1185.](https://onlinelibrary.wiley.com/doi/full/10.1111/ele.12648)
4. P.L. Shi, H. Shen, W.J. Wang, <span style="color:cornflowerblue">**Q. Yang**</span>, P. Xie. (2016) Habitat-specific differences in adaptation to light in freshwater diatoms. [**Journal of Applied Phycology**, 28(1): 227-239.](https://link.springer.com/article/10.1007/s10811-015-0531-7)
5. <span style="color:cornflowerblue">**Q. Yang**</span>, P. Xie, H. Shen, J. Xu, P. Wang and B. Zhang. (2012) A novel flushing strategy for diatom bloom prevention in the lower-middle Hanjiang River. [**Water Research**, 46(8): 2525-2534.](https://www.sciencedirect.com/science/article/abs/pii/S0043135412000838)
6. D.W. Zhang, <span style="color:cornflowerblue">**Q. Yang**</span>, P. Xie, X.W. Deng, J. Chen, and M. Dai. (2012) The role of cysteine conjugation in the detoxification of microcystin-LR in liver of bighead carp (Aristichthys nobilis): a field and laboratory study. [**Ecotoxicology**, 21(1): 244-252.](https://link.springer.com/article/10.1007/s10646-011-0783-1)
7. J. Xu, <span style="color:cornflowerblue">**Q. Yang**</span>, M. Zhang, P. Xie, and L.A. Hansson. (2011) Preservation effects on stable isotope ratios and consequences for the reconstruction of energetic pathways. [**Aquatic Ecology**, 45(4): 483-492.](https://link.springer.com/article/10.1007/s10452-011-9369-5)
8. <span style="color:cornflowerblue">**杨强**</span>, 谢平, 徐军, 沈宏, 张敏, 王松波, 王培丽. (2011) 河流型硅藻水华研究进展. 长江流域资源与环境, 20(z1): 159-165.



